POST https://giuxtaposition.tech/portfolio/contact
Content-Type: application/json

{
    "name": "Your alterego!",
    "email": "yg97.sm@gmail.com",
    "subject": "You're Hired!",
    "message": "Yes, you, exactly you, are hired! Aren't you happy?"
}
